### ISSUE TITLE
Provide name in transform

### ISSUE THREAD

**Issue by Nvveen** [openapi-ts/openapi-typescript#1054]
**Description**

I want to use the transform function to extract common enums from our API spec into separate type declarations (and even transform them into const arrays), by filtering by name. Currently this is not possible, because the transform function only provides the SchemaObject and Context as a parameter.

**Proposal**

Provide the `name` or `key` parameter as a third parameter to the transform function.

**Checklist**

- [x] I’m willing to open a PR for this (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))

**Comment by radist2s** [comment]
@drwpow, I too have encountered the need to know the `name` of a `schemaObject`, and also need access to the _parent_ `schemaObject`. This is necessary to be able to check `required` properties and to return the `questionToken` correctly.
What do you think about if we expand the number of accepted arguments for [`options.ctx.transform()`](https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-typescript/src/transform/schema-object.ts#L477C26-L477C47)?
I could prepare a PR along with a corresponding documentation update.
