### ISSUE TITLE
Polymorphic status code responses: ideas wanted!

### ISSUE THREAD

**Issue by drwpow** [openapi-ts/openapi-typescript#1128]
Say your endpoint returned entirely different shapes for `200`, `201`, `404`, and `500` responses. The current version of this library would assign `data` to `200`, and `error` to `500`, while ignoring the `201` and `404` responses altogether.

While this is the pattern that most endpoints follow—usually an endpoint will return _either_ `201` or `200` on success, but not both, which this library supports today—it still is a theoretical hiccup for valid schemas wanting to use this library.

Supporting this is unclear, though! How could this library provide support for multiple responses, **without the use of generics**?

**Option A: Response object** (breaking change)

```ts
const res = await get('/path/to/endpoint');
if (res[200]) { … }
else if (res[201]) { … }
else if (res[404]) { … }
else { … }
```

_Note: TS would throw an error on invalid keys, e.g. `res[0]`. Worth noting this is typed as an **object** with numeric indices, and not just a standard array._

**Option B: `response` discriminator** (non-breaking change)

```ts
const { data, error, response } = await get('/path/to/endpoint');
if (response.status === 200) { … }      // `data` is defined, has 200 shape
else if (response.status === 201) { … } // `data` is defined, has 201 shape
else if (response.status === 404) { … } // `error` is defined, has 404 shape
else { … }                              // `error` is defined, has 500 shape
```

**Option C: ???**

If you have another proposal, please submit one below!

**Comment by drwpow** [comment]
Update on this: the `response.status` discriminator support still hasn’t been added, and this issue will be complete once that’s in.

**Comment by EmilePerron** [comment]
I am very interested in this, and just wanted to add my support for going forward with Option B!

In the meantime, we use something of the sort to get the right types based on the status code:
```ts
if (response.error) {
  let error;

  switch (response.response.status) {
    case 400:
      error = response.error as paths["/rtm/notes/create"]["post"]["responses"]["400"]["content"]["application/ld+json"];
      break;
    case 422:
      error = response.error as paths["/rtm/notes/create"]["post"]["responses"]["422"]["content"]["application/ld+json"];
      break;
    // etc...
  }
```

It's not nearly as neat, but it kind of "works". 🤷‍♂️

**Comment by armandabric** [comment]
Hey there! We are having the same issue: our Open API schema contain multiple content types.

 Is it plan to be fixed in the next version (v7)? What can we do to help?

**Comment by RobinClowers** [comment]
I also support option B, I think checking status codes is a good practice anyway. I'm working with this api:
```
get_region: {
  responses: {
    200: {
      content: {
        "application/json": components["schemas"]["Region"];
      };
    }; 
    202: {
      content: {
        "application/json": components["schemas"]["Region"];
      };
    };
    204: {
      content: never;
    };
  };
};
```

Currently, `data` isn't type safe for this API, typescript will let me access properties of `Region` even though in the 204 case, there is no response body.
