### ISSUE TITLE
Handle error codes and failed request in error

### ISSUE THREAD

**Issue by vdawg-git** [openapi-ts/openapi-typescript#1179]
**Description**
Currently in order to handle errors the code usually looks something like this:
```typescript
const { data, error } = get('url/which/fails/to/fetch')
    .catch(error => ({error, response: new Response()}))

console.log(error) //=> TypeError: Failed to fetch
```
This is because a failed fetch is not getting caught by the library.
Which can also lead to Typescript not liking the new possible return type introduced by the catch.

**Proposal**

Instead this would be nicer:
```typescript
const { data, error } = get('url/which/fails/to/fetch')

console.log(error) //=> TypeError: Failed to fetch
```

I am not sure if I am simply doing something wrong, but having to do error handling twice can complicate things quite a lot.

The downside to this approach is that the previously unhandled errors cannot be typechecked/
However, they need to be handled in both cases anyway.

**Checklist**

- [x] I’m willing to open a PR for this (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-fetch/blob/main/CONTRIBUTING.md))

**Comment by drwpow** [comment]
Thanks for the suggestion. I’m a little hesitant to deviate from the default fetch behavior too much, which this library implements. If this library throws, then `fetch()` itself threw, which “shouldn’t happen”™. But to your point, this library is meant to provide better quality of life improvements over the default fetch spec. So whether that’s better documentation, or a typed error as you suggest, there’s definitely _some_ room for improvement here.
