### ISSUE TITLE
Error: ENOENT when generating schema from multiple `.yaml` files from another directory

### ISSUE THREAD

**Issue by bergac** [openapi-ts/openapi-typescript#1198]
**Description**

Error when generating schema from multiple `.yaml` files from another directory in the parent folder (see directory structure below).
Thus, the yaml file is not in the same folder as where the `package.json` is (because we reuse it for generation of code of another language).

The error I get is the following (note: I replaced the real directory with `$HOME`):

```
node:fs:600
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open '$HOME/api-contracts/typescript-generation/schemas/apis/views/DetailView.ts'
at Object.openSync (node:fs:600:3)
    at Object.writeFileSync (node:fs:2221:35)
    at generateSchema (file:///$HOME/api-contracts/typescript-generation/node_modules/openapi-typescript/bin/cli.js:125:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///$HOME/api-contracts/typescript-generation/node_modules/openapi-typescript/bin/cli.js:198:7
    at async Promise.all (index 0)
    at async main (file:///$HOME/api-contracts/typescript-generation/node_modules/openapi-typescript/bin/cli.js:188:3) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '$HOME/api-contracts/typescript-generation/schemas/apis/views/AllocationDetailView.ts'

```

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `6.2.8`                      |
| Node.js              | `v18.14.1`                      |
| OS + version         | `macOS 13.4.1` |

**Reproduction**

I have the following directory structure:
Directory structure:
```
api-contracts
+- apis
|   +- views
|   |   +- DetailView.yaml
|   +- typescript-generation
|   |  +- package.json    
```

And package.json looks like the following:
```
{
  "name": "typescript-generation",
  "version": "1.0.0",
  "description": "Typescript library for the API models",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "generate-views": "npx openapi-typescript \"../apis/views/**.yaml\" --output schemas/views/"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "openapi-typescript": "6.2.8"
  }
}

```

However, when I run `npx openapi-typescript ./../apis/views/**.yaml --output schemas/../../views/`, it works!
But the `DetailView.ts` is created in the `api-contracts/apis/views` folder.

I think the `outputFilePath` is mixed with the `inputFilePath`, while it should not, in `cli.js`:
```
const filename = pathToSpec.replace(EXT_RE, ".ts");
const originalOutputFilePath = outputFilePath;
outputFilePath = new URL(filename, originalOutputFilePath);
```

**Expected result**

Generate the `DetailView.ts` file in `api-contracts/typescript-generation/schemas/views/`.

**Checklist**

- [x] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
- [x] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))

**Comment by pvanagtmaal** [comment]
this might be fixed by #1281
