### ISSUE TITLE
Relative referenced yaml files results in a never type

### ISSUE THREAD

**Issue by Diokuz** [openapi-ts/openapi-typescript#1397]
**Description**

Relative referenced yaml files results in a never type.

```ts
export interface external {

  "bar.yaml": Record<string, never>
}
```

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `latest` (npx)                      |
| Node.js              | `18.12.1`                      |
| OS + version         | `macOS 13.4.1` |

**Reproduction**

<img width="130" alt="Screenshot 2023-10-19 at 12 11 55" src="https://github.com/drwpow/openapi-typescript/assets/2929442/25419669-f002-418c-b672-6b98bbd86da6">

`foo.yaml`

```yaml
openapi: '3.0.2'

info:
  title: title
  license:
    name: MIT
    url: http://example.com
  version: v1

servers:
  - url: http://example1.com
    description: 'description'

paths:
  /foo:
    get:
      security:
        - api_key: []
      summary: 'summary'
      operationId: 'operationId'
      responses:
        '200':
          description: 'description'
          content:
            application/json:
              schema:
                allOf:
                  - $ref: 'bar.yaml#/components/schemas/User'
        '404':
          description: 'description'
          content:
            application/json:
              schema:
                allOf:
                  - $ref: 'bar.yaml#/components/schemas/User'

components:
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      description: 'description'
      in: query

```

`bar.yaml`

```yaml
openapi: '3.0.2'

info:
  title: title
  license:
    name: MIT
    url: http://example.com
  version: v1

servers:
  - url: http://example1.com
    description: 'description'

paths:
  /foo:
    get:
      security:
        - api_key: []
      summary: 'summary'
      operationId: 'operationId'
      responses:
        '200':
          description: 'description'
          content:
            application/json:
              schema:
                type: object
                title: 'title'
                properties:
                  countryCode:
                    allOf:
                      - $ref: '#/components/schemas/User'

        '404':
          description: 'description'
          content:
            application/json:
              schema:
                type: object
                title: 'title'
                properties:
                  countryCode:
                    allOf:
                      - $ref: '#/components/schemas/User'

components:
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      description: 'description'
      in: query
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 4
        name:
          type: string
          example: Arthur Dent
      # Both properties are required
      required:
        - id
        - name

```

cli command

```
npx openapi-typescript ./schema2/foo.yaml -o ./schema.d.ts
```

**Expected result**

`schema.d.ts`

```ts
...
export interface operations {

  operationId: {
    /** summary */
    responses: {
      /** @description description */
      200: {
        content: {
          "application/json": external["bar.yaml"]["components"]["schemas"]["User"];
        };
      };
      ...
    };
  };
}
```

where ` external["bar.yaml"]["components"]["schemas"]["User"]` is a normal type.

**Actual result**

`schema.d.ts`

```ts
...
export interface external {

  "bar.yaml": Record<string, never>
}
...
```

**Checklist**

- [x] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))

So, is it possible to handle types in `bar.yml`?

**Comment by drwpow** [comment]
v6 supports remote schemas; this may just be a small bug in this specific scenario. Will investigate.

Also give v7 (`openapi-typescript@next`) a try and see if that works for you. Schema resolution has been greatly improved (and would love any feedback / bug reports / encountered issues if you do try that)

**Comment by omgpiu** [comment]
It's similar for my problem.  I have remote root yaml, but referenced yaml doesn't show their types. Bumped to 6.7.0
`export interface paths {
  '/foo': external['paths/foo-api/foo-api.yaml']
}`

`export interface external {
  'paths/foo-api/foo-api.yaml': {
    /** Search for foo */
    get: unknown
  }`

**Comment by drwpow** [comment]
@omgpiu sometimes the `unknown` can stem from a hard-to-find syntax error, such as accidentally omitting the `schema` key in the response. And 6.x does not validate your schema, so it won’t tell you if there are any issues.

7.x generates more `nevers` on purpose ([explanation](https://github.com/drwpow/openapi-typescript/issues/1368#issuecomment-1792226037)). The fact that both versions fail seem like it’s a syntax issue. But maybe it’s a bug. Would have to see your full schema to be sure.
