### ISSUE TITLE
Ability to omit schema objects from generated types

### ISSUE THREAD

**Issue by psychedelicious** [openapi-ts/openapi-typescript#1461]
**Description**

I'd like to be able to omit schema objects from generated types.

Use case:
My project has a plugin type system that results in additional schema objects being added to the OpenAPI schema at runtime. The application parses the schema at runtime to present these plugins to the user in the frontend.

As I am working on the application, I have some plugins installed. When I re-generate types, all of my plugin schemas are included, adding a lot of useless bulk to the types, which are committed to the app repo.

I'd like to use the transform APIs to exclude these plugin schemas entirely from my types.

My workaround is simple - I temporarily disable my plugins when generating the types, but I wonder if my request might be a useful feature for the library.

**Proposal**

- Add an export to the library `export const EXCLUDE_TYPE = Symbol("EXCLUDE_TYPE")`
- Exclude the type if the return value from `transform()` or `postTransform()` is the exclude token

**Checklist**

- [x] I’m willing to open a PR for this (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md))

**Comment by drwpow** [comment]
This sounds reasonable. I’ve gotten multiple requests to expand the transform API to fundamentally change your schema into something different, which I’m against. Changing your schema ad-hoc probably shouldn’t be done; or if you _do_ need to, use a tool like Redocly. 

However, _omitting_ is something entirely different and something I think is easy to support.

I also like your backwards-compatible suggestion that allows skipping via a symbol. We still need to reserve `undefined`/`void` to allow the transformer to skip the node and leave as-is. So deleting the node would require something like this approach (sidenote: other tools like Rollup usually rely on another callback to handle skipping, but I’m slightly-against having a `preTransform()` API—that feels like overcomplicating it.).

**Comment by psychedelicious** [comment]
I haven't had time for this but hope to in the future, if it isn't picked up by anybody else.
