### ISSUE TITLE
Generated types causes compiler errors

### ISSUE THREAD

**Issue by tonyxiao** [openapi-ts/openapi-typescript#1481]
When generating types for Slack & Discord I'm getting the following issue

Slack
https://api.apis.guru/v2/specs/slack.com/1.7.0/openapi.json
![CleanShot 2023-12-10 at 00 47 48@2x](https://github.com/drwpow/openapi-typescript/assets/696842/badf1791-a043-4629-8e49-67051d75d3b1)

Discord
https://raw.githubusercontent.com/discord/discord-api-spec/main/specs/openapi.json
<img width="1155" alt="image" src="https://github.com/drwpow/openapi-typescript/assets/696842/fd25c422-3fc9-4f0b-a53d-16e027221ca5">

I checked neither specs pass the redocly linter. However I wonder if there is a way for us to still generate types that doesn't cause typescript to completely error out and user has to manually resort to `@ts-ignore`

**Checklist**

- [ ] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
Does not pass unfortunately
- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md))

**Comment by drwpow** [comment]
Will take a look. I think in the Slack one, that can be fixed as we can just prevent `[key: string]: Record<string, never>` from being generated—that’s just noise (that should only happen if there are no other properties)

The Discord one is less straightforward, but it’s also worth looking into. Will look at what that specific schema object is, and see if there’s a better way to generate that.

**Comment by drwpow** [comment]
With the Slack schema, Swagger 2.0 is no longer supported with more recent versions of `openapi-typescript`. We can push security patches to 5.x and older versions, but not introducing breaking changes to how those generate.

Unfortunately, with the Discord error, that is a circular reference which is unresolvable. There’s not really a way to fix that in openapi-typescript. But with a tool like [Redocly custom plugins](https://redocly.com/docs/cli/custom-plugins/), you can import a schema, apply modifications, and then openapi-typescript can operate on the transformed result (when it comes to rewriting a schema, that’s something Redocly is better suited for than this library).

I see you referenced one error per schema for both; if there are other more specific errors you find in those examples I can investigate further.
