### ISSUE TITLE
Missing Types for Pattern, MaxLength, MinLength

### ISSUE THREAD

**Issue by joshuamil** [openapi-ts/openapi-typescript#1594]
**Missing Type Definitions for Pattern, MaxLength, MinLength**

_When trying to validate an OpenAPI 3 specification that is using Patterns, MaxLength, and MinLength for string and other data types, I get type errors when trying to use the aforementioned properties. I'm using 42Crunch for security audit and validation of generated API specifications, and it complains about these being missing. In the short-term, I've used `x-pattern` and the like, and then simply replace the text before writing the file programmatically. Obviously, that's not ideal, and is only a workaround in one specific use-case. If you're trying to validate a specification that has these supported properties, it will fail._

```
Paste full error message
```

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `^2.0.0`                     |
| Node.js              | `21.5.0`                     |
| OS + version         | `macOS Sonoma (14.4)`        |

**Reproduction**

_You can reproduce this by defining an API request, response, or schema and using the following property:_

```
someParamName:
  type: string
  example: Here is a sample
  maxLength: 50
  pattern: ^.{1,50}$
  description: Sample Param Name
  nullable: false
```

**Expected result**

_Should not get type errors when using supported properties maxLength, minLength, and pattern._

**Checklist**

- [x] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
- [x] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md))

**Comment by joshuamil** [comment]
Here's the TypeScript error as it occurs when using the `SchemaObject` type
![image](https://github.com/drwpow/openapi-typescript/assets/1080695/7004dc3d-7819-41c0-9dd3-af520b13cbec)

**Comment by drwpow** [comment]
I have a couple questions:

1. Is `2.x` the correct openapi-typescript version you’re using (not 6.x)? 6.x is recommended for OpenAPI 3 (which isn’t even supported below 5.x)
2. `type: string` will always generate into a `string` type in TypeScript; there won’t be any `maxLength` property on a string. If you look at the generated output for `someParamName`, **What does it generate now? What is the expected TypeScript you would like it to generate?**
