### ISSUE TITLE
Remove nanoid

### ISSUE THREAD

**Issue by imranbarbhuiya** [openapi-ts/openapi-typescript#1712]
**Description**
_A brief description of the bug. Provide either a screenshot or the full error message_

Hi, thanks for this awesome lib, the new version added `nanoid` for middleware usage, I'm using this package in my rn project and `crypto` isn't available there. Not only rn but there's other platforms/runtimes too where crypto available so adding that to dep and using it even when we arent using middleware makes it impossible for me to update. For now, I patched the package to remove `nanoid`. I can create a pr to fix it but need to discuss what should we use instead.

**Reproduction**
_How can this be reproduced / when did the error occur? Does the issue occur in a specific browser, or all browsers?_
Use the package in any env where crypto isn't available

**Expected result**
It should work and specially when I'm not even using middleware so id is useless for me.
_(in case it’s not obvious)_

**Checklist**

- [x] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-fetch/CONTRIBUTING.md))

**Comment by drwpow** [comment]
I’m not particular about the library used; it’s swappable. Actually looking at benchmarks I would like to use something faster, but without incurring weight. I may even end up handrolling something because it doesn’t need to be secure, or that unique (it can collide much more often because it’s only meant to compare requests right next to each other, not months apart)

**Comment by imranbarbhuiya** [comment]
can we use simple `Math.random().toString(36).slice(2, 11)`?

**Comment by drwpow** [comment]
> can we use simple `Math.random().toString(36).slice(2, 11)`?

That’s not a bad suggestion! Though this is something I do want to split hairs on to at least match nanoid’s performance and ideally beat if possible. For many libraries that’s overkill, but a design decision of this library is to be at the center of every fetch request it should be functionally equivalent to native `fetch()` and be as thin and performant as absolutely possible. So microoptimizations are important here IMO.

**Comment by drwpow** [comment]
The package’s [CONTRIBUTING guide](https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md#testing) has some basic instructions on test setup. You can also inspect `.github/workflows/ci.yml` to see the exact commands CI runs (which happens on a clean environment so it contains all the setup)

Also make sure you have pnpm 9 (current) and Node 22 (current) installed.

**Comment by imranbarbhuiya** [comment]
we should also need to skip generating the id when no middleware is registered

**Comment by drwpow** [comment]
Fixed in `0.10.1`. Also @imranbarbhuiya took both your suggestions, thank you! 🙂 The code provided is suitable for our purposes and sufficiently fast/minimal (it doesn’t need to be cryptographically-secure, and collisions don’t have to be super-unlikely either).

**Comment by imranbarbhuiya** [comment]
Thanks
