### ISSUE TITLE
When calling the client in nodeJS, I get an Array of ts.Node

### ISSUE THREAD

**Issue by loick** [openapi-ts/openapi-typescript#1713]
**Description**

Hi, I'm not using openapi-typescript as described in the Readme through `npx`, instead I have a nodeJS file I'm calling directly. In this file, I'm importing `openapi-typescript` and then I write the file myself with the content generated: 

```js
import generate from 'openapi-typescript'

import { baseUrl } from '../constants.js'

const content = await generate(`${baseUrl}/openapi.json`)

fs.writeFile('./src/schema.generated.d.ts', content, (err) => {
```

the generate function used to output a `string`, while now it's outputting a `ts.Node[]`. 

How do we get back the string from this Array? Thanks 🙏

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `7.0.0`                      |
| Node.js              | `20.13.1`                      |
| OS + version         | `macOS 14.5` |

**Comment by loick** [comment]
If someone ends up here, I didn't find the documentation at first but it's here: https://github.com/openapi-ts/openapi-typescript/blob/main/docs/node.md

**Comment by drwpow** [comment]
Ah glad you found it. Yes there’s also a mention in the Migration Guide  as well. It can be a bit intimidating at first but using the TS AST directly will allow for some even more powerful customizations! And of course you can still just convert it back to a string and do it the “old” way too with the tools included. You just have more options available now
