### ISSUE TITLE
Request headers are not sent

### ISSUE THREAD

**Issue by adamsykes-partnersense** [openapi-ts/openapi-typescript#1714]
**Description**

In version 0.10.0 the headers does not seem to be added. Tho you can still see them in the headers list if you log in the middleware the resulting request does not seem to use them.

**Reproduction**
I noticed it by my backend erroring since a header was missing.

This does not work:
```
const response = await client.GET('/my-endpoint', {
   headers: {
     'my-header': 'something'
   }
});
```

Neither does setting it on the client directly:
```
export const client = createClient<paths>({
  baseUrl: 'https://....',
  headers: {
     'my-header': 'something'
  },
});
```
If helpful i noticed when poking around in the files that changing line 117 in the compiled /dist/index.js

from
```
let response = await fetch(request.url, request);
```

to
```
let response = await fetch(request.url, {
  headers: request.headers
});`
```

will actually work. So I'm assuming there is something going on with the request object there.

**Expected result**

Header to be sent with it!

**Checklist**

- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-fetch/CONTRIBUTING.md))

**Comment by drwpow** [comment]
I’m not able to reproduce this myself; I’m seeing headers passed both in a browser and in Node.js (18, 20, and 22). Are you able to look at [all the existing header tests](https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-fetch/test/index.test.ts#L735) and determine how your setup differs from what’s currently being tested (e.g. are you using a custom fetch? are you in another env such as Deno we’re not testing?). I think there’s another missing piece here to your setup that’s causing headers to get missed; I don’t believe that line change you suggested is the root of the problem though.

**Comment by staticpo** [comment]
I had the same issue today, in a NextJS 14 project that follows [the example in the docs](https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-fetch/examples/nextjs/app/page.tsx).

Headers are not sent, even though they would seem to be there at build time. Adding a console.log in the coreFetch function and running the build command will output the auth headers I was adding, but they seem to be ignored on run time.

In a regular native fetch without this library, my auth headers works correctly.

**Comment by adamsykes-partnersense** [comment]
Seems to me this was fixed in a newer version, so closing this issue. Nice!
