### ISSUE TITLE
Use in Next.js's middleware.ts causes error

### ISSUE THREAD

**Issue by SkelatorIndy** [openapi-ts/openapi-typescript#1718]
**Description**

When using the openapi-fetch client in Next.js 14.2.4's `middleware.ts` file, it causes the app to error

**Client Error**
![image](https://github.com/openapi-ts/openapi-typescript/assets/13159212/c76538e0-2f0c-4642-af6e-d7803c2abdd2)

**Server Error**
![image](https://github.com/openapi-ts/openapi-typescript/assets/13159212/76eea27e-652b-4dcf-9c52-4ed55219e5d5)

**Reproduction**

This can be reproduced by using the openapi-fetch client in the `middleware.ts` file of Next.js. The error does not occur if you use the standalone fetch client

**Causes Error:**
```
// Located in another file
const api = createClient<paths>({
  baseUrl: 'https://localhost:5000',
});

export default async function middleware(request: NextRequest) {
  await api.GET('/api/v1/auth/security');

  return Response.redirect(new URL('/', request.url));
}
```

**Works:**
```
export default async function middleware(request: NextRequest) {
  await fetch('http://localhost:5000/api/v1/auth/security');

  return Response.redirect(new URL('/', request.url));
}
```

I made a sandbox using the latest version of Next.js showing this error occurring with a very minimal setup:
[Sandbox Reproduction](https://codesandbox.io/p/devbox/openapi-typescript-reproduction-77g9gh?file=%2Fmiddleware.ts%3A15%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxp88bbq00062069mc2xkaat%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxp88bbq00022069aojaj5uq%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxp88bbq00042069urg1ofu6%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxp88bbq00052069jrylzmzt%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxp88bbq00022069aojaj5uq%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxp88bbq00012069b22mslts%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clxp8kb1700022069j7past4k%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A15%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A15%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fmiddleware.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clxp88bbq00022069aojaj5uq%2522%252C%2522activeTabId%2522%253A%2522clxp8kb1700022069j7past4k%2522%257D%252C%2522clxp88bbq00052069jrylzmzt%2522%253A%257B%2522id%2522%253A%2522clxp88bbq00052069jrylzmzt%2522%252C%2522activeTabId%2522%253A%2522clxp88ml0002m20690wpyvty4%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clxp88ml0002m20690wpyvty4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clxp88bbq00042069urg1ofu6%2522%253A%257B%2522id%2522%253A%2522clxp88bbq00042069urg1ofu6%2522%252C%2522activeTabId%2522%253A%2522clxp8hizf00j52069zht3c3gf%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxp88bbq00032069a2o8awft%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clxp8hizf00j52069zht3c3gf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clxp8hj07008bdjge663g421p%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Expected result**

Should be able to use openapi-fetch in `middleware.ts`

**Checklist**

- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-fetch/CONTRIBUTING.md))

**Comment by drwpow** [comment]
I believe this is a duplicate of #1569 ?

**Comment by SkelatorIndy** [comment]
The solution of manually replacing the fetch for the request with the standalone fetch does work, and because of the small scope of where this error occurs it is not a bad solution. However, since that issue mentioned a fix being merged in, and the follow up mentions specifically that the GET requests are fine, which mine is not, I was unsure if this may be a separate but related issue. However, if you do believe it is a duplicate of the same issue mentioned there, then this issue can be closed as a duplicate.

**Comment by FreeAoi** [comment]
I'm going to take a look at the issue, I'm supposed to have made a PR trying to resolve this but it doesn't seem to cover some cases.

**Comment by jhenkehd** [comment]
@FreeAoi There is no PR linked with this issue, has this been resolved in the mean time?
