### ISSUE TITLE
Enum option cannot generate enums if values are not valid property names

### ISSUE THREAD

**Issue by jekh** [openapi-ts/openapi-typescript#1722]
**Description**

When there are multiple keys that cannot be represented as properties, the generated enum converts them all to `_`, which makes it impossible to use those values in the enum.

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `7.0.0`                      |
| Node.js              | `20`                      |
| OS + version         | `Linux` |

**Reproduction**

A decent example is the Intercom OpenAPI spec: https://github.com/intercom/Intercom-OpenAPI/blob/main/descriptions/2.11/api.intercom.io.yaml

When generating types using:
```sh
openapi-typescript ./api.intercom.io.yaml --enum -o ./intercom.d.ts
```

It results in an enum that looks like this:
```ts
export enum Single_filter_search_requestOperator {
    _ = "=",
    _ = "!=",
    IN = "IN",
    NIN = "NIN",
    _ = "<",
    _ = ">",
    _ = "~",
    _ = "!~",
    _ = "^",
    $ = "$"
}
```

**Expected result**

Quoted key names if they are not valid javascript properties. For example, something like this:
```ts
export enum Single_filter_search_requestOperator {
    "=" = "=",
    "!=" = "!=",
    IN = "IN",
    NIN = "NIN",
    "<" = "<",
    ">" = ">",
    "~" = "~",
    "!~" = "!~",
    "^" = "^",
    $ = "$"
}
```

**Checklist**

- [ ] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md))

**Comment by drwpow** [comment]
Great, reproducible example, thank you! This PR would be a great simple fix if someone is able to provide one.

**Comment by dsinghvi** [comment]
@jekh The Intercom folks have released a new alpha version of their SDK (https://github.com/intercom/intercom-node/discussions/416). Would you be interested in giving that a swing?

**Comment by drwpow** [comment]
Yes I believe so! But if anyone notices any additional issues, please let us know.
