### ISSUE TITLE
bug: request body fields with default values are treated as required

### ISSUE THREAD

**Issue by ysemennikov** [openapi-ts/openapi-typescript#1741]
**Description**

We have generated TS interfaces using our OpenAPI 3.1.0 specification. There are some parameters that have default values (so they are not required in request, and the body without them will be still valid):

<img width="1424" alt="image" src="https://github.com/openapi-ts/openapi-typescript/assets/52397003/4b52c73f-9041-478b-b0fa-6ff548f8cfe2">

However, these parameters are treated as required when generating paths:

<img width="1064" alt="image" src="https://github.com/openapi-ts/openapi-typescript/assets/52397003/250a8613-a584-495d-8244-a3c59ecfd622">

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `7.0.1`                      |
| Node.js              | `20.13.1`                      |
| OS + version         | `macOS Sonoma 14.4` |

**Reproduction**

Try to use this openapi schema:

```json
"src__schemas__social_profiles__Create": {
  "properties": {
    "card_title": {
      "type": "string",
      "maxLength": 64,
      "minLength": 1,
      "title": "Card Title",
      "default": "Social Profile"
    },
    "template": {
      "type": "string",
      "maxLength": 64,
      "minLength": 1,
      "title": "Template"
    },
    "photo": {
      "anyOf": [
        {
          "type": "string",
          "maxLength": 2083,
          "minLength": 1,
          "format": "uri"
        },
        {
          "const": ""
        }
      ],
      "title": "Photo",
      "default": ""
    },
    "signature": {
      "anyOf": [
        {
          "type": "string",
          "maxLength": 2083,
          "minLength": 1,
          "format": "uri"
        },
        {
          "const": ""
        }
      ],
      "title": "Signature",
      "default": ""
    },
    "design": {
      "type": "object",
      "title": "Design",
      "default": {

      }
    },
    "details": {
      "type": "object",
      "title": "Details",
      "default": {

      }
    },
    "socials": {
      "type": "object",
      "title": "Socials",
      "default": {

      }
    },
    "meta": {
      "type": "object",
      "title": "Meta",
      "default": {

      }
    }
  },
  "type": "object",
  "required": [
    "template"
  ],
  "title": "Create",
  "description": "Social Profile schema for create."
}
```

You can see that default values are set, but the fields are not recognized as not required.

**Expected result**

Parameters that have default values have `| undefined` in type declaration, like
```ts
type SocialProfileCreate = {
    card_title: string;
    template: string;
    photo?: string | "";
    signature?: string | "";
    design?: Record<string, never>;
    details?: Record<string, never>;
    socials?: Record<string, never>;
    meta?: Record<string, never>;
}
```

**Checklist**

- [x] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md))

**Comment by phk422** [comment]
> **Description**
> 
> We have generated TS interfaces using our OpenAPI 3.1.0 specification. There are some parameters that have default values (so they are not required in request, and the body without them will be still valid):
> 
> <img alt="image" width="1424" src="https://private-user-images.githubusercontent.com/52397003/345621263-4b52c73f-9041-478b-b0fa-6ff548f8cfe2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNTU3NTksIm5iZiI6MTcyMDA1NTQ1OSwicGF0aCI6Ii81MjM5NzAwMy8zNDU2MjEyNjMtNGI1MmM3M2YtOTA0MS00NzhiLWIwZmEtNmZmNTQ4ZjhjZmUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDAxMTA1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiNzMzMjYwMmQ0OTMxZGMwZWQ4ZGQzZTczMDRlNmIyMDJjNjc1N2I5ZWNhYzQ5MGNjYjNmNTdkZTQ4MTA5ZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o_7TQQS7m5sFG9lBCbcokWQqtve1f4T3vwFj8jHhrMQ">
> However, these parameters are treated as required when generating paths:
> 
> <img alt="image" width="1064" src="https://private-user-images.githubusercontent.com/52397003/345620598-250a8613-a584-495d-8244-a3c59ecfd622.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNTU3NTksIm5iZiI6MTcyMDA1NTQ1OSwicGF0aCI6Ii81MjM5NzAwMy8zNDU2MjA1OTgtMjUwYTg2MTMtYTU4NC00OTVkLTgyNDQtYTNjNTllY2ZkNjIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDAxMTA1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjYTRkYzQ1ODg4ODQwNzZmNzI2Nzc0OTExY2Q4NzE4MDRmY2Q4OWE4Y2I4MTgyNjM3MTNkOTZjNzcyMmYxOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gCEQMswdHBKKh2Dn-ITprZamgm5z8s4itBzWXj_ZIjg">
> Name	Version
> `openapi-typescript`	`7.0.1`
> Node.js	`20.13.1`
> OS + version	`macOS Sonoma 14.4`
> **Reproduction**
> 
> Try to use this openapi schema:
> 
> ```json
> "src__schemas__social_profiles__Create": {
>   "properties": {
>     "card_title": {
>       "type": "string",
>       "maxLength": 64,
>       "minLength": 1,
>       "title": "Card Title",
>       "default": "Social Profile"
>     },
>     "template": {
>       "type": "string",
>       "maxLength": 64,
>       "minLength": 1,
>       "title": "Template"
>     },
>     "photo": {
>       "anyOf": [
>         {
>           "type": "string",
>           "maxLength": 2083,
>           "minLength": 1,
>           "format": "uri"
>         },
>         {
>           "const": ""
>         }
>       ],
>       "title": "Photo",
>       "default": ""
>     },
>     "signature": {
>       "anyOf": [
>         {
>           "type": "string",
>           "maxLength": 2083,
>           "minLength": 1,
>           "format": "uri"
>         },
>         {
>           "const": ""
>         }
>       ],
>       "title": "Signature",
>       "default": ""
>     },
>     "design": {
>       "type": "object",
>       "title": "Design",
>       "default": {
> 
>       }
>     },
>     "details": {
>       "type": "object",
>       "title": "Details",
>       "default": {
> 
>       }
>     },
>     "socials": {
>       "type": "object",
>       "title": "Socials",
>       "default": {
> 
>       }
>     },
>     "meta": {
>       "type": "object",
>       "title": "Meta",
>       "default": {
> 
>       }
>     }
>   },
>   "type": "object",
>   "required": [
>     "template"
>   ],
>   "title": "Create",
>   "description": "Social Profile schema for create."
> }
> ```
> 
> You can see that default values are set, but the fields are not recognized as not required.
> 
> **Expected result**
> 
> Parameters that have default values have `| undefined` in type declaration, like
> 
> ```ts
> type SocialProfileCreate = {
>     card_title: string;
>     template: string;
>     photo?: string | "";
>     signature?: string | "";
>     design?: Record<string, never>;
>     details?: Record<string, never>;
>     socials?: Record<string, never>;
>     meta?: Record<string, never>;
> }
> ```
> 
> **Checklist**
> 
> * [x]  My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
> * [ ]  I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md))

Hi, @ysemennikov ! The results I generated using your scheme test were correct.
![image](https://github.com/openapi-ts/openapi-typescript/assets/59734322/ce15d94d-3db9-4f7d-a8fc-62045d80b0f7)

**Comment by duncanbeevers** [comment]
@phk422 We're seeing this issue as well. Could the difference be that the requestBody is using a referenced component schema rather than an inline schema?

**Comment by ysemennikov** [comment]
> @phk422 We're seeing this issue as well. Could the difference be that the requestBody is using a referenced component schema rather than an inline schema?

Hi @phk422, the requestBody in our OpenAPI schema was also referenced, not inline. Maybe this really makes sense?

**Comment by phk422** [comment]
> > @phk422 We're seeing this issue as well. Could the difference be that the requestBody is using a referenced component schema rather than an inline schema?
> 
> Hi @phk422, the requestBody in our OpenAPI schema was also referenced, not inline. Maybe this really makes sense?

Ah, yes, I overlooked it. I already submitted a pr to fix it!
