### ISSUE TITLE
Setup section in npm and the docs are not similar

### ISSUE THREAD

**Issue by Magnuti** [openapi-ts/openapi-typescript#1748]
**Description**

The Setup section on [npmjs.com](https://www.npmjs.com/package/openapi-typescript#setup) is not identical to the Setup section on [https://openapi-ts.dev](https://openapi-ts.dev/introduction#setup).

It took me a while to find out why the types did not work. It was because this part was missing from the npm site.

![image](https://github.com/openapi-ts/openapi-typescript/assets/43852515/7b7e6da6-13d2-46f9-8828-9f86e897436f)

**Proposal**

The documentation should be identical across websites.

**Checklist**

- [ ] I’m willing to open a PR for this (see [CONTRIBUTING.md](https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md))

**Comment by drwpow** [comment]
Thanks for raising! This can be fixed by copying info from `docs/` into `packages/openapi-typescript/README.md`. This would be a great simple docs fix for someone.

**Comment by phk422** [comment]
> Thanks for raising! This can be fixed by copying info from `docs/` into `packages/openapi-typescript/README.md`. This would be a great simple docs fix for someone.

Oh! @drwpow, I found that copying might have some issues because some syntax in the docs directory is specific to VitePress. This could cause inconsistencies when displayed on npmjs compared to our website. I think the simplest solution is to directly link to our official website. What do you think?

**Comment by drwpow** [comment]
@phk422 Yes we do link to the docs already.

My personal preference for packages is to have the **minimal setup** present in the README / on npm just to make it easier for folks. And link to the docs beyond basic setup.

This does require some manual copying, but as it’s only 2 packages that have docs, and the setup section doesn’t change that frequently, it’s not a burden at the moment.
