### ISSUE TITLE
Inject option dropped in v7

### ISSUE THREAD

**Issue by johnnymetz** [openapi-ts/openapi-typescript#1754]
**Description**

Version 6 had an `inject` options, which allowed you to import arbitrary TS types at the beginning of the file, see docs: https://openapi-ts.pages.dev/6.x/node#options

This option no longer exists but I need it. Is there still a way to do this or has this support been dropped completely?

**Proposal**

_Outline the change to the library. If this is for the CLI, propose a flag name and/or workflow. If this is for Node API, propose how this would be consumed. Reference any prior art or similar examples._

Re-implement the `inject` option, see code: https://github.com/openapi-ts/openapi-typescript/pull/1363/files#diff-aa2bf9eceec4d8c746802aaaeaa09f72333c8a8983ef9e956fdc3c71c972bda7L117-L118

**Checklist**

- [ ] I’m willing to open a PR for this (see [CONTRIBUTING.md](https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md))

**Comment by kerwanp** [comment]
Hey @johnnymetz, the feature has been recently released (thanks to @phk422 #1766 !). The documentation: https://openapi-ts.dev/node#options

I'm closing the issue has this should be resolved, feel free to open a new one if necessary!
