### ISSUE TITLE
Document for conditional authentication failed.

### ISSUE THREAD

**Issue by tcztzy** [openapi-ts/openapi-typescript#1756]
**Description**

[Document for conditional authentication](https://openapi-ts.dev/openapi-fetch/middleware-auth#conditional-auth) failed. The code in documentation failed with error
```
TypeError: Cannot read properties of undefined (reading 'startsWith')
```
**Reproduction**

Just follow the document

**Expected result**

`url` should be passed to `onRequest`

https://github.com/openapi-ts/openapi-typescript/blob/69f0628b5ad22c3535c43653b70bd8fbc5f3887d/packages/openapi-fetch/src/index.js#L110-L116

https://github.com/openapi-ts/openapi-typescript/blob/69f0628b5ad22c3535c43653b70bd8fbc5f3887d/packages/openapi-fetch/src/index.d.ts#L127-L145

**Checklist**

- [x] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-fetch/CONTRIBUTING.md))

**Comment by Mask-MJ** [comment]
I'm not sure if this is the best practice: url -> schemaPath
```
const UNPROTECTED_ROUTES = ["/v1/login", "/v1/logout", "/v1/public/"];

const authMiddleware = {
  onRequest({ schemaPath, request }) {
    if (UNPROTECTED_ROUTES.some((pathname) => schemaPath.startsWith(pathname))) {
      return undefined; // don’t modify request for certain paths
    }

    // for all other paths, set Authorization header as expected
    request.headers.set("Authorization", `Bearer ${accessToken}`);
    return request;
  },
};
```

**Comment by kerwanp** [comment]
@tcztzy You are right, url is not passed along.

I think we should simply remove it as it is already present in the `request` parameter.
And anyway, I think that the example could not work as `url` might be the absolute url. The @Mask-MJ solution works great.

If you want to open a PR, feel free to submit one by referencing this issue! It should be as simple a simply removing the `url` parameter from the type. (and updating the documentation to use schemaPath).
