### ISSUE TITLE
transform function changing objects to not-nullable no longer working in v7

### ISSUE THREAD

**Issue by IGx89** [openapi-ts/openapi-typescript#1758]
**Description**

Hello! When my OpenAPI v3.0 spec has something like this:
```json
  "foo": {
      "allOf": [
          {
              "$ref": "#/components/schemas/Bar"
          }
      ],
      "nullable": true
  },
```
And my transform is this:
```js
    transform(schemaObject) {
      // Treat optional AND nullable fields as just optional (possibly undefined)
      if (!schemaObject.required && schemaObject.nullable) {
        schemaObject.nullable = false;
      }
    },
```

with v6 I was getting the following:
```ts
foo?: components["schemas"]["Bar"];
```

but with v7 I'm now getting:
```ts
foo?: components["schemas"]["Bar"] | null;
```

Is this expected behavior? What can I do to make v7 work like v6 did here? The logic appears to still work for primitive type fields, but no longer for object refs.

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `7.0.2`                      |
| Node.js              | `20.15.1`                      |
| OS + version         | `Windows 11` |

**Checklist**

- [ ] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
- [x] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md))

**Comment by phk422** [comment]
> **Description**
> 
> Hello! When my OpenAPI v3.0 spec has something like this:
> 
> ```json
>   "foo": {
>       "allOf": [
>           {
>               "$ref": "#/components/schemas/Bar"
>           }
>       ],
>       "nullable": true
>   },
> ```
> 
> And my transform is this:
> 
> ```js
>     transform(schemaObject) {
>       // Treat optional AND nullable fields as just optional (possibly undefined)
>       if (!schemaObject.required && schemaObject.nullable) {
>         schemaObject.nullable = false;
>       }
>     },
> ```
> 
> with v6 I was getting the following:
> 
> ```ts
> foo?: components["schemas"]["Bar"];
> ```
> 
> but with v7 I'm now getting:
> 
> ```ts
> foo?: components["schemas"]["Bar"] | null;
> ```
> 
> Is this expected behavior? What can I do to make v7 work like v6 did here? The logic appears to still work for primitive type fields, but no longer for object refs.
> 
> Name	Version
> `openapi-typescript`	`7.0.2`
> Node.js	`20.15.1`
> OS + version	`Windows 11`
> **Checklist**
> 
> * [ ]  My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
> * [x]  I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md))

In V7, the transform operates after the type generation, so attempting to change schemaObject directly will not take effect. but, you can use the following method to modify the type, I think it's very flexible:
```ts
import transformSchemaObject from 'openapi-typescript/dist/transform/schema-object.ts'

function transform(schemaObject, options) {
  // Treat optional AND nullable fields as just optional (possibly undefined)
  if (!schemaObject.required && schemaObject.nullable) {
    schemaObject.nullable = false;
    return transformSchemaObject(schemaObject, options)
  }
}
```

**Comment by IGx89** [comment]
Thanks a lot! Would not have figured that out myself, don't see that function (nor the odd import) in the docs. Setting questionToken to true broke other things (`foo?: string` became `foo?: string | undefined`) but the following worked:

```ts
      if (!schemaObject.required && schemaObject.nullable) {
        schemaObject.nullable = false;
        return transformSchemaObject(schemaObject, options);
      }
```

**Comment by phk422** [comment]
> ```ts
> transformSchemaObject
> ```

This weird function import I mentioned a pr for - #1759
