### ISSUE TITLE
openapi-fetch: example for extending api client methods

### ISSUE THREAD

**Issue by Amixx** [openapi-ts/openapi-typescript#1760]
Hello! First of all, thanks for this tool, I find it very useful!

I have a question regarding modification to api client methods. Let's say I want to always return the data property after calling the GET request. How do I declare the correct parameter and return types for this method?

```
const apiClient = createClient<paths, 'application/ld+json'>({ /* removed for brevity */ })

const getData = (...args: any /* TODO: get argument types */): Promise<any /* TODO: get return type */> => {
  return (await apiClient.GET(...args))?.data
}
```

I tried to implement it based on the types in the package and got to something like this:

```
const getData = async <
    Path extends PathsWithMethod<paths, 'get'>,
    Init extends MaybeOptionalInit<paths[Path], 'get'>,
  >(
    url: Path,
    ...init: HasRequiredKeys<Init> extends never
      ? [(Init & { [key: string]: unknown })?]
      : [Init]
  ): Promise<
    FetchResponse<paths[Path]['get'], Init, 'application/ld+json'>['data']
  > => {
    return (await apiClient.GET(url, init)).data
  }
```

but there are two errors:

![image](https://github.com/user-attachments/assets/d7bd58e4-ea2a-4d49-acc7-6be422535cd6)
![image](https://github.com/user-attachments/assets/eea6ece7-e23d-4be3-9ef5-4ff6f400bbed)

and my attemt is not really ideal because it depends on many internal types, so I am looking for a more ideomatic way to accomplish this. It would be nice if an example for stuff like this would be in the docs.

Sorry if the issue is formatted wrongly, I will update it if needed.

**Comment by kerwanp** [comment]
Hey @Amixx,
I've done something similar for the openapi-react-query package, maybe you will find what you need with the following type: https://github.com/openapi-ts/openapi-typescript/pull/1717/files?diff=unified&w=0#diff-50b08a9645fe85e543902c82e96b837307b0d80b1717eec7c465e63c838ff090R15

**Comment by Amixx** [comment]
Thanks @kerwanp! This looks like what I needed.
