### ISSUE TITLE
Default values override "required" state in output types

### ISSUE THREAD

**Issue by dave-addition** [openapi-ts/openapi-typescript#1776]
**Description**

Generated types don't allow `undefined` inputs on fields with default values, even if they're not part of the `"required"` fields array.

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `7.0.2`                      |
| Node.js              | `v20.12.2`                      |
| OS + version         | `macOS 14.5` |

**Reproduction**

Create a `package.json` like:

```
{
  "name": "test-scripts",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "http-server -p 4000",
    "generate": "tsx ./generate-types.ts > ./openapi-output.ts"
  },
  "dependencies": {
    "openapi-typescript": "7.0.2",
    "tsx": "4.7.1",
    "typescript": "5.4.5"
  },
  "devDependencies": {
    "http-server": "14.1.1"
  },
  "author": "",
  "license": "ISC"
}

```

Add a `docs-json` file with:

```
{
  "openapi": "3.0.0",
  "security": [
    {
      "bearer": []
    }
  ],
  "paths": {
    "/do/the/thing": {
      "post": {
        "operationId": "Controller_method",
        "summary": "Do something.",
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/MyInputType"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Did the thing."
          },
          "400": {
            "description": "Bad request."
          }
        }
      }
    }
  },
  "info": {
    "title": "Test API",
    "license": {
      "name": "MIT",
      "url": "https://opensource.org/license/mit"
    },
    "description": "",
    "version": "1.0",
    "contact": {}
  },
  "tags": [],
  "servers": [
    {
      "url": "https://some.site.com/v1"
    }
  ],
  "components": {
    "securitySchemes": {
      "bearer": {
        "scheme": "bearer",
        "bearerFormat": "JWT",
        "type": "http"
      }
    },
    "schemas": {
      "MyInputType": {
        "type": "object",
        "properties": {
          "requiredField": {
            "type": "string"
          },
          "optionalField": {
            "type": "string"
          },
          "optionalFieldWithDefault": {
            "type": "string",
            "default": "foo"
          }
        },
        "required": [
          "requiredField"
        ]
      }
    }
  }
}
```

and a `generate-types.ts` file with:

```
import openapiTS from "openapi-typescript";
import ts, { EmitHint } from "typescript";

openapiTS("http://127.0.0.1:4000/docs-json", {
  alphabetize: true,
}).then((output) => {
  const outFile = ts.createSourceFile("API.ts", "", ts.ScriptTarget.Latest);
  const printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed });
  output.forEach((typeNode) => {
    console.log(printer.printNode(EmitHint.Unspecified, typeNode, outFile));
  });
});
```

Run `yarn start` in one terminal window and `yarn generate` in another. This creates an `openapi-output.ts` file.

**Expected result**

I expect a schema which looks like this:

```
        MyInputType: {
            optionalField?: string;
            /** @default foo */
            optionalFieldWithDefault?: string;
            requiredField: string;
        };
```

But this is what the script outputs:

```
        MyInputType: {
            optionalField?: string;
            /** @default foo */
            optionalFieldWithDefault: string;
            requiredField: string;
        };
```

I'm surprised by this because the `"required"` array is part of the offical JSON schema spec, whereas the `default` value is (to the best of my knowledge) not. The closest thing I could find to documentation was [here](https://swagger.io/specification/#schema-object), where the docs say:

> Unless stated otherwise, the property definitions follow those of JSON Schema and do not add any additional semantics.

So I would expect the `?` types to be determined by `"required"` fields only.

**Checklist**

- [x] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md)) (I _may_ be open to this, but don't want to commit to it as I'm not familiar with this project and unsure how tough it would be)

**Comment by phk422** [comment]
@dave-addition You can take part in this：https://github.com/openapi-ts/openapi-typescript/pull/1746#issuecomment-2221874701

**Comment by dave-addition** [comment]
Thanks!
