### ISSUE TITLE
openapi-react-query: support for useQueries()

### ISSUE THREAD

**Issue by michalfedyna** [openapi-ts/openapi-typescript#1807]
@drwpow @kerwanp Do you guys think that it's possible to add support for `useQueries()`? I'll work on that but need some directions and opinions.

**Comment by kerwanp** [comment]
Hey! This definitely needs to be supported in the future!

I was thinking of something like this, I'm not a big fan of the "array tupple" so if you have a better idea feel free to share!

```tsx
  const userQueries = $api.useQueries({
    queries: users.map((user) => ['get', '/api/users/{id}', { params: {  path: { id: user.id } } }]),
  })
```

**Comment by michalfedyna** [comment]
I'll work on that over the weekend, I'll keep you updated.
