### ISSUE TITLE
Document Japanese support

### ISSUE THREAD

**Issue by yoshi2no** [openapi-ts/openapi-typescript#1815]
**Description**

I would like to add Japanese documentation for Japanese users, similar to the Chinese support addressed in [this issue](https://github.com/openapi-ts/openapi-typescript/issues/1560). I have the time to work on this, so if it seems like a good idea, I’d like to proceed. 

**Proposal**

- Add Japanese documentation. 
  - similar to docs/zh, add a docs/ja directory and include the translation files.

**Checklist**

- [x] I’m willing to open a PR for this (see [CONTRIBUTING.md](https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md))

**Comment by drwpow** [comment]
That would be incredible, and much appreciated! Thank you!

Yes just adding a `ja` folder and following the same approach should work.

**Comment by drwpow** [comment]
As always, docs are always a work in progress, and future additions are always welcome! But thanks @yoshi2no for doing all the hard parts done and getting it up ❤️
