### ISSUE TITLE
ResolveError: Failed to load https://****.*****.com/****/****: 404 Not Found

### ISSUE THREAD

**Issue by Jacobify** [openapi-ts/openapi-typescript#1829]
**Description**

After updating the package from [6.7.6](url) to [7.3.0](https://github.com/openapi-ts/openapi-typescript/releases/tag/openapi-typescript%407.3.0) I see the below error log when fetching data from certain URLs that I need to build my app with,
Basically it is a simple `npm i` which inside runs `npm run tsDefinition:****:****`.

When I `curl -I my-url`  , I get a `200 OK` message but during the build it fails and returns `404 Not Found`.
I am not sure where this issue is arising from so I would appreciate some insights/ideas for a solution.
Works perfect until version [6.7.6](https://github.com/openapi-ts/openapi-typescript/releases/tag/openapi-typescript%406.7.6)
But breaks from [7.0.0](https://github.com/openapi-ts/openapi-typescript/releases/tag/openapi-typescript%407.0.0)
```
npm run tsDefinition:****:**** exited with code 1
/builds/*****/******/node_modules/@redocly/openapi-core/lib/resolve.js:113
 throw new ResolveError(error);
 ResolveError: Failed to load https://****.******.com/****/****: 404 Not Found
```

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `7.3.0`                      |
| Node.js              | `20.11.1`                      |
| OS + version         | `Windows 11` |

**Reproduction**

**described in the description**

**Checklist**

- [ ] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md))

**Comment by kerwanp** [comment]
Hi, it is hard to debug your issue without any proper way to reproduce it.

There is a really high chance that the problem is on your side. When using curl, make sure that you also use the same method and headers.

If you have access, you could also try to trace the request from the backend to see why it returns a 404.

**Comment by Jacobify** [comment]
This is the command that returns the error :

`openapi-typescript https://****.****.com/*****/***** --output src/app/*******/@types/API.d.ts -m POST`

I thought maybe removing `-m POST` would have an effect but it did not.

What do you think can help me address this issue better ? 

PS.
I saw this change on the version [7.0.0](https://github.com/openapi-ts/openapi-typescript/releases/tag/openapi-typescript%407.0.0)

![image](https://github.com/user-attachments/assets/ed4d9e57-b251-4402-879a-7b53918b1189)

And I prefer not the create a separate config file if there is another way to address this error.

**Comment by Jacobify** [comment]
> Hi, it is hard to debug your issue without any proper way to reproduce it, can you include the code that triggers the request?
> 
> There is a really high chance that the problem is on your side. When using curl, make sure that you also use the same method and headers.
> 
> If you have access, you could also try to trace the request from the backend to see why it returns a 404.

And to answer your last question , I have no access to the BE at all .

**Comment by drwpow** [comment]
So the fetch mechanism _technically_ changed from 6.x to 7.x, but only in that it moved from undici to [node-fetch via Redoy](https://github.com/Redocly/redocly-cli/blob/main/packages/core/src/utils.ts#L62). Redocly is a very widely-used tool though, and nothing it’s doing is nonstandard that I can see, and this is the first report we’ve gotten. So it could be possible that your backend os responding in a very nonstandard way from the slightest difference in request, and not giving you any hints.

Fortunately, you can specify `customFetch` in your Redoc config, so you can start debugging by replacing that with undici to see if you get a response again. But I agree with @kerwanp in that this seems like a problem to this specific endpoint which other users aren’t having, and we can’t debug ourselves without more info. But hopefully this gives you a lead to figure out what’s different yourself.

**Comment by htunnicliff** [comment]
Since this issue appears to be related to either a specific OpenAPI endpoint or a network failure, it seems unlikely that openapi-typescript is causing the issue.
