### ISSUE TITLE
Help wanted: split type & runtime tests for openapi-fetch

### ISSUE THREAD

**Issue by drwpow** [openapi-ts/openapi-typescript#1852]
For openapi-fetch, most of our tests live in a single `index.test.ts` file. Instead, we should separate them into at least 2:

- `runtime.test.ts`: tests the runtime, such as: _Did the correct headers get sent? Did query params serialize correctly? Did the JSON get parsed correctly? Is FormData handled? etc_
- `types.test-d.ts`: basically the bulk of tests: _Are we showing required params correctly? Optional params? Are we handling `data`/`error` correctly? What about all the options?_

The `*.test-d.ts` file uses [Vitest type checking](https://vitest.dev/guide/testing-types.html) and should make more use of `expectTypeOf()` and other helpers to **make more granular assertions.** This would help make triaging bugs like https://github.com/openapi-ts/openapi-typescript/issues/1845, https://github.com/openapi-ts/openapi-typescript/issues/1798, and https://github.com/openapi-ts/openapi-typescript/issues/1525 easier.

**Comment by Pete-Fowler** [comment]
Taking a look and will submit a PR or comment here if unable to.
