### ISSUE TITLE
Help wanted: add size-limit check in CI

### ISSUE THREAD

**Issue by drwpow** [openapi-ts/openapi-typescript#1853]
`openapi-fetch` as it’s grown in features has grown in size! It was originally `2 kb` when it started out, but with middleware support and other features is now closer to `6 kb` (technically `5.8 kb` but who’s counting?—wait we need to!).

Adding something like [Size Limit](https://evilmartians.com/chronicles/size-limit-make-the-web-lighter) (or something else) in CI to make sure the bundle size doesn’t **increase** would be helpful. The goal of this check isn’t to prevent any features or bugfixes if they add to the weight at all, rather, it just helps prevent **unintentional size increases.** We can always decide to increase the package weight if it provides value for the weight.

**Comment by jeiea** [comment]
Can this be closed?

**Comment by drwpow** [comment]
Yes! I had thought this closed; thanks for the ping
