### ISSUE TITLE
[Latest v6] Provide message when generated type cannot be resolved so generator will use unknown

### ISSUE THREAD

**Issue by jakubjosef** [openapi-ts/openapi-typescript#1906]
**Description**

We are using `openapi-typescript` in our development workflow and it works great, however we needed to change the schema a little to make it work.

What we did:
1) Added add defined objects to `components.schemas` in api.yaml 
2) Maintain correct order of them, if `A` uses `B` via ref, `B` needs to defined before `A` otherwise output object will be `unknown`

If we have some issue in object definitions or object order, result will be `unknown`. Our schema changes a lot by developers which are not directly consuming it (their backend generator works as expected with given change). My team is maintaining TS types generated by `openapi-typescript` and we are facing above-mentioned error pretty often.

**Proposal**

When openapi-typescript code face some issue and it's not able to generate TS type for some schema object, it should print some error/warning. 

If possible this error should be helpful to identify and fix schema issue, but even error itself can help - we can have CI pipeline to detect it and fail PR for problematic commit.

Following image shows error output:
![Snímek obrazovky 2024-09-09 v 22 45 42](https://github.com/user-attachments/assets/4e667bf8-1a27-41fa-b9ff-44c6d37d3372)

Let me know if you something from my side (more schema examples, etc.)

I'm using version 6.7.6.
**I tested latest v7 version and it works better, but because of different output structure we cannot easily migrate there now.**

**Comment by drwpow** [comment]
Limitations in 6.x’s resolver logic are what led to the rewrite in 7.x. The original intent was to preserve your schema closer to “as-written,” so the structure is preserved. But in practice, almost all schemas need to be introspected (to handle things like optional keys) and resolved as one object, like you said.

A good workaround is to use the Redocly CLI’s bundle command to flatten your schema into one file, then run 6.x on that. It should do a much better job on a single file.

Beyond that, though, unfortunately this is a flaw in 6.x’s resolvers that isn’t easy to fix. It’s not that we don’t want to fix it; it would basically be a rewrite of 6.x.
