### ISSUE TITLE
[openapi-react-typescript] discrepency between queryOptions and other hook

### ISSUE THREAD

**Issue by tifosiblack** [openapi-ts/openapi-typescript#1929]
**Description**

Thanks for the new queryOptions, it's really useful for prefetching queries in the route loaders. However I have a small issue with queryOptions. The third parameter seems required, even when no parameters is expected.

![image](https://github.com/user-attachments/assets/16d529a3-6341-4a44-866f-993df17a9cda)

vs

![image](https://github.com/user-attachments/assets/e172bcde-b701-45fb-be5a-b5f5ccfaf87e)

![image](https://github.com/user-attachments/assets/7b930e6e-d86c-4a7b-ae3b-410d323f69e9)

**Reproduction**

Last Typescript version (don't know if it matters), an endpoint in the openapi which doesn't need any parameter.
queryOptions should behave the same than other hooks.

**Expected result**

queryOptions always requires a third parameter (an empty object do the trick however).

**Checklist**

- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-fetch/CONTRIBUTING.md))

**Comment by lukasbash** [comment]
Experiencing the same issue and also noted it in the one I opened (https://github.com/openapi-ts/openapi-typescript/issues/1946).
What is weird is that it works if you initialize the options to a variable before you pass them to any function call.
