### ISSUE TITLE
Generates incorrect dynamic path with `integer` parameters 

### ISSUE THREAD

**Issue by kleinepls** [openapi-ts/openapi-typescript#1930]
**Description**

Using the `--path-params-as-types` flag, the library doesn't generate the `number` type for OpenAPI `integer` type dynamic path parameters. It leaves it as `integer`, which is an invalid type in TypeScript.

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `7.4.0`                      |
| Node.js              | `20.17.0`                      |
| OS + version         | `Pop!_OS, kernel 6.9.3-76060903` |

**Reproduction**

Generate with the `--path-params-as-types` flag off of this example:
```
openapi: 3.0.0
info: 
  title: "test" 
components:
  schemas: {}
paths: 
  /user/{user_id}/profile:
    get:
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
```

Result (omitting unrelated fields):
```
export interface paths {
    [path: `/user/${integer}/profile`]: {
        get: {
            parameters: {
                path: {
                    user_id: number; <- notice how this one is generated correctly.
                };
            };
        };
```

**Checklist**

- [ ] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
- [x] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md))

**Comment by prewk** [comment]
This line gets `type: 'integer'` in the schema and writes it out:

https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-typescript/src/transform/paths-object.ts#L58

**Comment by prewk** [comment]
Sure, I'll give it go!

**Comment by prewk** [comment]
There.
