### ISSUE TITLE
punycode deprecated - still need?

### ISSUE THREAD

**Issue by ghferrari** [openapi-ts/openapi-typescript#1939]
**Description**
Use of this package produces a warning that `punycode` is deprecated (see below for full message).

Is this package still needed? I don't see it being used anywhere. If it's not being used, can it be deleted from `pnpm-lock.yaml`?

Paste full error message
```
[DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
```

**Comment by drwpow** [comment]
This is a duplicate, and not caused by this package. It’s upstream in Redocly. See https://github.com/Redocly/redocly-cli/issues/1332#issuecomment-2393651000

**Comment by htunnicliff** [comment]
Looks like there may be an upstream fix for this shortly:

- https://github.com/Redocly/redocly-cli/pull/1848
