### ISSUE TITLE
The throwing middleware implementation available in the documentation is not working

### ISSUE THREAD

**Issue by darkbasic** [openapi-ts/openapi-typescript#1954]
**Description**

The documentation explains how to throw errors instead of returning them:
```ts
onResponse({ response }) {
  if (response.error) {
    throw new Error(response.error.message);
  }
}
```

Unfortunately it seems to be wrong because I get `Property 'error' does not exist on type 'Response'`:

![image](https://github.com/user-attachments/assets/ed34ec9b-bc3a-4f8f-bd51-e1de1c9b78e8)

It's not just a matter of bad typings: the error prop just isn't there.

**Reproduction**

Copy-paste the throwing middleware snippet from the documentation and look for the typing error.

**Expected result**

The error should be available somewhere if we want to be able to throw it.

**Checklist**

- [x] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-fetch/CONTRIBUTING.md))

**Comment by jo-m** [comment]
A better example could be

```ts
  onResponse({ response }) {
    if (response.ok) {
      return undefined
    }

    // Will produce error messages like "404 Not Found".
    throw new Error(`${response.status} ${response.statusText}`)
  }
```

**Comment by drwpow** [comment]
Thank you for raising! Would love a small PR to update this

**Comment by darkbasic** [comment]
@drwpow @jo-m unfortunately this is still not satisfactory because data will remain an union with undefined, forcing you to check if error is not empty even if the error won't happen outside of the catch block:

![image](https://github.com/user-attachments/assets/6651c5ba-0e35-4bfb-9869-b6d3866f84e5)

**Comment by jo-m** [comment]
I think there is no way to achieve that via a middleware, because that would have to change the type signature of the client object.

So, you'd have to implement a wrapper around the client object which throws, and removes `error` from the type signature.

**Comment by jo-m** [comment]
1. Again, a middleware cannot do this because it cannot change the type signature.
2. If you want to submit a PR for a wrapper, [this](https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-react-query/src/index.ts#L108) is probably a good starting point.

**Comment by darkbasic** [comment]
> Again, a middleware cannot do this because it cannot change the type signature.

That's why I said it should be embedded in the codebase, otherwise you cannot change the type signature.

> If you want to submit a PR for a wrapper, [this](https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-react-query/src/index.ts#L108) is probably a good starting point.

The point is: will openapi-fetch accept such PR?

**Comment by jo-m** [comment]
@drwpow Would you accept a contribution like this:

```typescript
import createClient, {
  Client,
  ClientMethod,
  ClientOptions,
  InitParam,
  MaybeOptionalInit,
  Middleware,
  ParseAsResponse,
} from "openapi-fetch"
import {
  HttpMethod,
  MediaType,
  PathsWithMethod,
  ResponseObjectMap,
  SuccessResponse,
} from "openapi-typescript-helpers"

type SuccessfulFetchResponse<
  T extends Record<string | number, any>,
  Options,
  Media extends MediaType,
> = {
  data: ParseAsResponse<SuccessResponse<ResponseObjectMap<T>, Media>, Options>
  response: Response
}

type ThrowingClientMethod<
  Paths extends Record<string, Record<HttpMethod, {}>>,
  Method extends HttpMethod,
  Media extends MediaType,
> = <
  Path extends PathsWithMethod<Paths, Method>,
  Init extends MaybeOptionalInit<Paths[Path], Method>,
>(
  url: Path,
  ...init: InitParam<Init>
) => Promise<SuccessfulFetchResponse<Paths[Path][Method], Init, Media>>

interface ThrowingClient<Paths extends {}, Media extends MediaType = MediaType> {
  GET: ThrowingClientMethod<Paths, "get", Media>
  PUT: ThrowingClientMethod<Paths, "put", Media>
  POST: ThrowingClientMethod<Paths, "post", Media>
  DELETE: ThrowingClientMethod<Paths, "delete", Media>
  OPTIONS: ThrowingClientMethod<Paths, "options", Media>
  HEAD: ThrowingClientMethod<Paths, "head", Media>
  PATCH: ThrowingClientMethod<Paths, "patch", Media>
  TRACE: ThrowingClientMethod<Paths, "trace", Media>
  use(...middleware: Middleware[]): void
  eject(...middleware: Middleware[]): void
}

export class APIError extends Error {
  public readonly method: HttpMethod
  public readonly response: Response
  public readonly errorPayload: any

  constructor(method: HttpMethod, response: Response, errorPayload: any) {
    super(`${method.toUpperCase()} ${response.url}: ${response.status} ${response.statusText}`)
    this.name = "APIError"
    this.method = method
    this.response = response
    this.errorPayload = errorPayload
  }
}

async function wrap<
  Paths extends Record<string, Record<HttpMethod, {}>>,
  Method extends HttpMethod,
  Media extends MediaType,
  Path extends PathsWithMethod<Paths, Method>,
  Init extends MaybeOptionalInit<Paths[Path], Method>,
>(
  client: Client<Paths, Media>,
  method: Method,
  url: Path,
  ...init: InitParam<Init>
): Promise<SuccessfulFetchResponse<Paths[Path][Method], Init, Media>> {
  const mth = method.toUpperCase() as Uppercase<typeof method>
  const fn = client[mth] as ClientMethod<Paths, typeof method, Media>
  // TODO: find a way to avoid as any.
  // Copied from https://github.com/openapi-ts/openapi-typescript/blob/455b73527c788918d665a3d607e8ac240a4e5e52/packages/openapi-react-query/src/index.ts#L117
  const { data, error, response } = await fn(url, ...(init as any))

  if (error) {
    throw new APIError(method, response, error)
  }

  if (!data) {
    throw new APIError(method, response, "No data and no error received")
  }

  return { data: data!, response }
}

// Like `createClient()` from "openapi-fetch", but the client will additionally
// throw an `APIError` on non-2XX responses.
//
// Usage example with complete error handling:
//
//     import createThrowingClient, { APIError } from "throwingClient"
//     import { paths } from "my-generated-client-package"
//
//     const client = createThrowingClient<paths>({ baseUrl: "/" })
//     try {
//       const { response, data } = await client.POST("/api/v1/auth/signin", {
//         body: {
//           username: "admin",
//           password: "REPLACEME",
//         },
//       })
//       console.log(response.status, data.token)
//     } catch (error: unknown) {
//       if (error instanceof APIError) {
//         console.error("=== APIError ===", error.message, error.errorPayload)
//       } else if (error instanceof Error) {
//         console.error("=== Fetch Error ===", error)
//       } else {
//         console.error("=== Unknown Error ===", error)
//       }
//     }
export default function createThrowingClient<Paths extends {}, Media extends MediaType = MediaType>(
  clientOptions?: ClientOptions,
): ThrowingClient<Paths, Media> {
  const client = createClient<Paths, Media>(clientOptions)

  return {
    GET: (url, ...init) => wrap(client, "get", url, ...init),
    PUT: (url, ...init) => wrap(client, "put", url, ...init),
    POST: (url, ...init) => wrap(client, "post", url, ...init),
    DELETE: (url, ...init) => wrap(client, "delete", url, ...init),
    OPTIONS: (url, ...init) => wrap(client, "options", url, ...init),
    HEAD: (url, ...init) => wrap(client, "head", url, ...init),
    PATCH: (url, ...init) => wrap(client, "patch", url, ...init),
    TRACE: (url, ...init) => wrap(client, "trace", url, ...init),
    use(...middleware: Middleware[]) {
      client.use(...middleware)
    },
    eject(...middleware: Middleware[]) {
      client.eject(...middleware)
    },
  }
}
```

With example usage:

```typescript
import createThrowingClient, { APIError } from "throwingClient"
import { paths } from "my-generated-client-package"

const client = createThrowingClient<paths>({ baseUrl: "/" })
try {
  const { response, data } = await client.POST("/api/v1/user/login", {
    body: {
      username: "REPLACEME",
      password: "SUPERSECRET",
    },
  })
  console.log(response.status, data.token)
} catch (error: unknown) {
  if (error instanceof APIError) {
    console.error("=== APIError ===", error.message, error.errorPayload)
  } else if (error instanceof Error) {
    console.error("=== Fetch Error ===", error)
  } else {
    console.error("=== Unknown Error ===", error)
  }
}
```

This wraps the existing `Client`, does not break any existing code, and could easily coexist.

**Comment by darkbasic** [comment]
@jo-m I would make it an option of `createClient` instead of creating a separate `createThrowingClient`

**Comment by darkbasic** [comment]
Also we cannot simply throw a standard `Error` because we need to provide the additional properties returned by the server with the error response. So we need to create our own Error class and instantiate it.

**Comment by jo-m** [comment]
> @jo-m I would make it an option of `createClient` instead of creating a separate `createThrowingClient`

I do not think this is ergonomic and possible whilst keeping compile time type safety. Can you propose a type signature for `createClient()` that would work?

---

> Also we cannot simply throw a standard Error because we need to provide the additional properties returned by the server with the error response. So we need to create our own Error class and instantiate it.

Yeah, there is `APIError`, but unfortunately the error property is of type `any`. I am not a TS/JS expert, but as far as I know, TS does not offer any typing for Errors and try/throw/catch, so there is no way to have some kind of APIError<T> which contains the error response from your oapi spec in a type safe manner. Except if you'd pass in some user-supplied extractor method for the error message on every call, but that's not really in the spirit of this I think.

**Comment by darkbasic** [comment]
> I do not think this is ergonomic and possible whilst keeping compile time type safety.

I think it can be done with conditional typings.

> Can you propose a type signature for createClient() that would work?

That would depend on the answer to the following question:

> will openapi-fetch accept such PR?

Won't be trivial for sure, but I think it's possible.

**Comment by darkbasic** [comment]
> Yeah, there is APIError, but unfortunately the error property is of type any. I am not a TS/JS expert, but as far as I know, TS does not offer any typing for Errors and try/throw/catch, so there is no way to have some kind of APIError which contains the error response from your oapi spec in a type safe manner.

That's a valid point and I didn't think about it. It somehow reduces the utility of the typings. We could narrow the type down with type predicates but it would require some hinting (the path would need to be specified twice).
At this point it makes more sense to keep the throwing middleware disabled by default and enable it **per call** when you need it. Which means moving the config from `createClient` to the GET/POST/PUT/DELETE options.

**Comment by darkbasic** [comment]
Should this be converted into a Discussion?

**Comment by darkbasic** [comment]
@jo-m does that mean that openapi-fetch will merge such PR? I might be willing to implement it but only if there is interest in getting it merged. That's why I asked to convert this issue into a discussion.

**Comment by jo-m** [comment]
@darkbasic I don't know, I am not a maintainer. This issue as originally reported is about something completely different (docs), which is now fixed, so it makes sense it is closed.

You can just start a new PR and use the code I pasted above as a starting point for discussion, that's almost 0 work for you.

**Comment by pipech** [comment]
This is what I also encounter and really think there should be an option or config to throw error when return is not 2xx.

This is a temporary fix I come up as a work around.

**To summarize the fix**

- Remove `data?: never` from [`FetchResponse`](https://github.com/openapi-ts/openapi-typescript/blob/5a38e160c5f00914b9e8b8c024b429d09c081f27/packages/openapi-fetch/src/index.d.ts#L101-L111), the other typed part is just copied from original.
- Cast new type to client using `as`.

```ts
import type {
  HttpMethod,
  MediaType,
  PathsWithMethod,
  ResponseObjectMap,
  SuccessResponse,
} from "openapi-typescript-helpers";

import createClient, {
  type InitParam,
  type MaybeOptionalInit,
  type Middleware,
  type ParseAsResponse,
} from "openapi-fetch";

import { type paths } from "./schema";

export class HttpError extends Error {
  public errors?: Record<string, string>;
  public message: string;
  public statusCode: number;

  constructor(props: {
    statusCode: number; message: string; errors?: Record<string, string>;
  }) {
    super(props.message);
    this.name = "HttpError";
    this.statusCode = props.statusCode;
    this.message = props.message;
    this.errors = props.errors;

    // Ensures that instances of HttpError have the correct prototype chain in environments that don't support native ES6 classes.
    Object.setPrototypeOf(this, HttpError.prototype);
  }
}


/**
 * Config.
 * ---
 * We'll use middleware to throw error if response status is not 2xx
 * because it's behavior tanstack-react-query expects.
 *
 * And since we change behavior, data will always exists if function not throw error.
 * So we need these type below to make type of data not undefined.
 */

// Only change to type is the `FetchResponse` by removing `data?: never` part.
// Other than that just copied from `openapi-fetch/dist/index.d.ts`
type FetchResponse<T extends Record<number | string, any>, Options, Media extends MediaType> =
  {
    data: ParseAsResponse<SuccessResponse<ResponseObjectMap<T>, Media>, Options>;
    response: Response;
  };

export type ClientMethod<
  Paths extends Record<string, Record<HttpMethod, {}>>,
  Method extends HttpMethod,
  Media extends MediaType,
> = <Path extends PathsWithMethod<Paths, Method>, Init extends MaybeOptionalInit<Paths[Path], Method>>(
  url: Path,
  ...init: InitParam<Init>
) => Promise<FetchResponse<Paths[Path][Method], Init, Media>>;

interface Client<Paths extends {}, Media extends MediaType = MediaType> {
  /** Call a GET endpoint */
  GET: ClientMethod<Paths, "get", Media>;
  /** Call a PUT endpoint */
  PUT: ClientMethod<Paths, "put", Media>;
  /** Call a POST endpoint */
  POST: ClientMethod<Paths, "post", Media>;
  /** Call a DELETE endpoint */
  DELETE: ClientMethod<Paths, "delete", Media>;
  /** Call a OPTIONS endpoint */
  OPTIONS: ClientMethod<Paths, "options", Media>;
  /** Call a HEAD endpoint */
  HEAD: ClientMethod<Paths, "head", Media>;
  /** Call a PATCH endpoint */
  PATCH: ClientMethod<Paths, "patch", Media>;
  /** Call a TRACE endpoint */
  TRACE: ClientMethod<Paths, "trace", Media>;
  /** Register middleware */
  use(...middleware: Middleware[]): void;
  /** Unregister middleware */
  eject(...middleware: Middleware[]): void;
}

const client = createClient({
  baseUrl: "https://v15-api.cafn.dev",
}) as Client<paths>;

// TanStack Query expects error to be thrown.
// """A query function can be literally any function that returns a promise.
// The promise that is returned should either resolve the data or throw an error."""
const throwErrorMiddleware: Middleware = {
  async onResponse({ request, response, options }) {
    if (!response.ok) {
      const { message } = await response.json();

      const fallbackErrorMessage = `${response.status} - ${request.url}`;
      const errorMessage = typeof (message) === "string" ? message : fallbackErrorMessage;

      throw new HttpError({
        statusCode: response.status,
        message: errorMessage,
        errors: {
          url: request.url,
          method: request.method,
        },
      });
    }
  },
};

client.use(throwErrorMiddleware);

export { client };
```
