### ISSUE TITLE
Repo Configuration: NPM_TOKEN updates needed for swr-openapi publishing

### ISSUE THREAD

**Issue by htunnicliff** [openapi-ts/openapi-typescript#1994]
@drwpow it looks like we may need an updated `NPM_TOKEN` secret for this repo in order to publish to swr-openapi:

https://github.com/openapi-ts/openapi-typescript/actions/runs/11727749276/job/32669572929#step:6:32

Your npm account should already have write permissions for the package, but it seems the token that exists today in this repo doesn't have the right access. 

Any chance you would be able to generate a new token?

**Comment by drwpow** [comment]
Ah good catch! Just updated, thanks. Will re-run the action to see if it worked

**Comment by drwpow** [comment]
Published!
