### ISSUE TITLE
openapi-react-query does not handle the server returning null

### ISSUE THREAD

**Issue by gaborbernat** [openapi-ts/openapi-typescript#2000]
When the server returns null (which is a valid thing, because e.g. has no payload to send) openapi-react-query handles that as an error, even though the server returned with 200.

The reason behind this is https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-react-query/src/index.ts#L118-L121, here this should be:

```js
    if (error || data === undefined) {
      throw error;
    }
    return data;
```

**Comment by kerwanp** [comment]
Hi, this is duplicate of https://github.com/openapi-ts/openapi-typescript/issues/1973 and a PR is currently opened https://github.com/openapi-ts/openapi-typescript/pull/1975
