### ISSUE TITLE
Unable to send correct optional path segments

### ISSUE THREAD

**Issue by nikcio** [openapi-ts/openapi-typescript#2010]
**Description**

_A brief description of the bug. Provide either a screenshot or the full error message_

When having a URL path where some of the path is optional it is not possible to send `undefined` or `null` as the parameter as it doesn't remove the path segment.

This is due to the following code:
https://github.com/openapi-ts/openapi-typescript/blob/c9ba9dc9a5f3d971594f015895c6585bef1d1052/packages/openapi-fetch/src/index.js#L491-L493

**Reproduction**

_How can this be reproduced / when did the error occur? Does the issue occur in a specific browser, or all browsers?_

Open API spec with optional path parameter for example: `https:localhost:5000/api/box/create/{source}`

In this example sending `https:localhost:5000/api/box/create` would mean create a new box and `https:localhost:5000/api/box/create/1234` create a new box by duplicating the box with id 1234.

Send a request using openapi-fetch client where you specify `null` or `undefined` in the path parameter (`source`).

**Expected result**

_(in case it’s not obvious)_

I want to be able to send `undefined` or `null` to remove a path parameter.

**Work around**

To work around this issue it is possible to send an empty string to bypass the check here:
https://github.com/openapi-ts/openapi-typescript/blob/c9ba9dc9a5f3d971594f015895c6585bef1d1052/packages/openapi-fetch/src/index.js#L491-L493

**Checklist**

- [x] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-fetch/CONTRIBUTING.md))

Options for solving this problem:

1. Remove the check
2. Allow overriding the `defaultPathSerializer` similarly to `querySerializer`
3. Allow feature toggle to allow `undefined` / `null` to remove values in the path

**Comment by htunnicliff** [comment]
Hi @nikcio, would you be able to share the whole OpenAPI schema for this route?

**Comment by nikcio** [comment]
Hey @htunnicliff sorry for the delay here is an example:

```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "Test",
    "version": "Latest"
  },
  "paths": {
    "/api/box/create/{source}": {
      "post": {
        "tags": [],
        "parameters": [
          {
            "name": "source",
            "in": "path",
            "allowEmptyValue": true,
            "schema": {
              "type": "integer",
              "format": "int32",
              "nullable": true
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/BoxCreate"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BoxCreateResponse"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "BoxCreate": {
        "type": "object",
        "properties": {
          "Name": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "BoxCreateResponse": {
        "type": "object",
        "properties": {
          "Message": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      }
    }
  }
}
```

In case it throws an error i adjusted it by hand to make it a minimal example 😄

**Comment by htunnicliff** [comment]
@nikcio Thank you for sharing this example – very helpful!

Looking at this schema, I think the behavior you are trying to achieve is not supported by OpenAPI. 

From [the spec](https://swagger.io/specification/v3/#fixed-fields-10): 

- `allowEmptyValue` may only be used for `query` parameters, not `path` parameters.
- `path` parameters must always have `required` set to `true`.

**Comment by nikcio** [comment]
Interesting. Well in that case it isn't a bug  😅

With that definition it might be the most correct to make two paths in the OpenApi spec then?

But luckily we can use the work around with sending an empty string until we can change our spec for generation.

**Comment by htunnicliff** [comment]
I think using two separate paths might make sense! And using refs you could keep the duplication to a minimum.
