### ISSUE TITLE
[Bug] cannot access relative/proxied URLs

### ISSUE THREAD

**Issue by Lakelimbo** [openapi-ts/openapi-typescript#2015]
**Description**

I have a backend using .NET, running under Aspire (tl;dr a thing to orchestrate projects under containers directly on code), and I am using Svelte for the frontend, so I made a proxy on Vite to target the backend.

**Reproduction**

Steps on C# are a bit out of scope, so I will leave that out (but I can make a reproduction repo if really needed). On Vite this is the proxy:
```js
export default defineConfig({
	plugins: [sveltekit()],
	server: {
		host: true,
		port: parseInt(process.env.PORT ?? '5173'),
		proxy: {
			'/api': {
				target:  <dotnet-url-coming-from-docker>,
				changeOrigin: true,
				rewrite: (path) => path.replace(/^\/api/, ''),
				secure: false
			}
		}
	},
	// ...
}
```
It works as intended when using regular `fetch()`, but when using OpenAPI-TS Fetch it does not work, it ignores the URL rewrite by Vite (somehow), going literally to `/api/<my-content>` rather than the proxied URI, resulting on a `ERR_INVALID_URL`.
One weird behavior is that even when using SvelteKit, on a `load` function, it still returns the same error with OpenAPI-TS Fetch even when I pass Kit's `fetch()` to it (which afaik uses Undici under the hood).
I guess this behavior comes from `createFinalURL()` (and subsequently from `defaultPathSerializer()`), but I'm not exactly sure; and it's also probably not a framework-specific issue.

**Environment**

- OS: Arch Linux
- Node.js v23.1.0
- NPM 10.9.0
- Svelte v5 (under SvelteKit)
- Browser: Zen (Firefox)

**Comment by htunnicliff** [comment]
Since openapi-fetch uses `globalThis.fetch` by default, I am inclined to believe that this problem is on the Vite side of things.

**Comment by afonsograca** [comment]
@htunnicliff in my case, when I create my client, I pass the custom fetch function, provided by SvelteKit, to initialise my client:
```typescript
export const handle: Handle = async params => {
 ...
  params.event.locals.api = createClient({
    fetch: params.event.fetch,
  })

  return params.resolve(params.event, {
    filterSerializedResponseHeaders(name) {
      return name === 'content-length'
    },
  })
}
```
and still find the same `ERR_INVALID_URL` issue. I've also tried passing the custom fetch in the request itself, like:
```typescript
client.POST('/api/auth', {
    body,
    fetch
  })
```
to the same result. Making the request concurrently with the custom fetch itself, I'm able to get a response.

I found a way to make it work, by setting the base URL during the client creation, like so:
```typescript
  params.event.locals.api = createClient({
    fetch: params.event.fetch,
    baseUrl: params.event.url.origin,
  })
 ```
 
 so, seeing that in these scenarios it shouldn't be using `globalThis.fetch`, could there be something going wrong in `openapi-fetch` itself?
 
 Cheers

**Comment by htunnicliff** [comment]
If I understand correctly, the client throws an error, but when you pass baseURL, the client works as expected?

If that is the case, I think that is the expected behavior of the client.
