### ISSUE TITLE
openapi-fetch@0.13.2 missing 'dist' in package

### ISSUE THREAD

**Issue by jgoz** [openapi-ts/openapi-typescript#2032]
**Description**

I happened to install the latest version (0.13.2) and noticed that the package is missing the `dist` directory. 0.13.1 is fine.

**Reproduction**

```
npm i openapi-fetch@0.13.2
ls -al node_modules/openapi-fetch
```

**Expected result**

_(in case it’s not obvious)_

**Checklist**

- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-fetch/CONTRIBUTING.md))

**Comment by bkis** [comment]
My build failing after installing `0.13.2` is probably related to this...

```
vite v6.0.1 building for production...
transforming...
✓ 434 modules transformed.
x Build failed in 2.50s
error during build:
[commonjs--resolver] Failed to resolve entry for package "openapi-fetch". The package may have incorrect main/module/exports specified in its package.json.
...
```

**Comment by xobotyi** [comment]
Same here, `0.13.2` lacks `dist` folder, `0.13.1` is fine

**Comment by eduhdev12** [comment]
Same issue, builds are failing 😕

**Comment by stefcameron** [comment]
I'm also seeing the same missing `./dist` in the recently-published `openapi-react-query@0.2.7` while `0.2.6` has the `./dist` directory...

**Comment by aguynamedben** [comment]
Same here, it's my first time using openapi-fetch and my editor couldn't find the import. yarn chose to install 0.13.2, which is published to npm but not documented on the GitHub releases page. Downgrading to 0.13.1 worked.

**Comment by gzm0** [comment]
@drwpow could this be because of the turborepo upgrade?

**Comment by drwpow** [comment]
Thanks for raising! This was a hiccup in our automated publish pipeline. Will have refreshes out shortly fixing the issue.

**Comment by drwpow** [comment]
> @drwpow could this be because of the turborepo upgrade?

Also just for internal reference, this _did_ happen in the Turborepo upgrade, but was 100% unrelated to Turborepo. This was the offending line:

https://github.com/openapi-ts/openapi-typescript/pull/2027/files#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34L24

```diff
-    - run: pnpm run build
```

There’s a weird quirk about the Changesets release where the `version` script doesn’t run every time. During the actual release, you do need to run `pnpm run build` independently of the `version` script (which also has a build inside). This behavior is undocumented. So I wrote a comment in `ci/.release.yml` reminding us should this ever happen again.

**Comment by drwpow** [comment]
openapi-fetch and openapi-react-query got refreshes (you’ll have to update to the latest patch; for obvious reasons npm doesn’t let you re-publish a version), and confirmed the `dist/` folder was published correctly. Sorry for the inconvenience!
