### ISSUE TITLE
Package not found on NPM

### ISSUE THREAD

**Issue by Aschen** [openapi-ts/openapi-typescript#2045]
The package is not on NPM anymore, any idea ?

![image](https://github.com/user-attachments/assets/e832604d-9296-4f3f-83e6-1c1eeedce2a5)

**Comment by dkacha** [comment]
I am fine https://www.npmjs.com/package/openapi-fetch

**Comment by Aschen** [comment]
yes it came back, strange bug but probably from NPM side 👍
