### ISSUE TITLE
Schema with private external ref

### ISSUE THREAD

**Issue by bsubba** [openapi-ts/openapi-typescript#244]
Is there any way that I can convert swagger definition with external ref which require authentication to typescript?

**Comment by drwpow** [comment]
We currently don’t support external refs. We’re currently thinking about a way to add it, as some refs may be remote, some may be local, some may require auth, per your original question. And in all cases, it’d be very hard to replicate Swagger remote refs in TypeScript, as we’d have to find some way to convert those to TS modules.

All that to say, it’s not that this will _never_ happen; it’ll just take a really big time commitment that the current maintainers don’t have. My recommendation would be to generate types for each schema separately for now.
