### ISSUE TITLE
Feature Request: Optionally support "extended" query string parsing structures

### ISSUE THREAD

**Issue by brianphillips** [openapi-ts/openapi-typescript#802]
I'm working with an OpenAPI spec that uses nested query string parameters (i.e. `page[number]=2`). [By default](https://expressjs.com/en/api.html#app.settings.table), this is parsed by Express using the [qs](https://www.npmjs.com/package/qs) module which converts that to a nested object that looks like `{"page":{"number":2}}` instead of the simple/flat representation that looks like `{"page[number]":2}`.

To be clear, this is functionality that has not yet made its way to the official OpenAPI spec (discussion [here](https://github.com/OAI/OpenAPI-Specification/issues/1706)) but given this is the default behavior for Express, I'm wondering whether it might make sense for this project to optionally support expanding the resulting types for query parameters out into their deeply nested form. Without this functionality, we are left with two less than perfect options:

- change Express to use the "simple" query parsing functionality (and change the app code that currently expects nested query string parameter values), or
- ignore the typing for the query parameters entirely and use the default types provided by `@types/express`

Is this something that would make sense to add into `openapi-typescript`? I can totally understand not wanting to deviate from the official spec so I'm somewhat expecting that to be the outcome but given the default behavior of Express, I would guess this is a fairly common pitfall to experience when trying to wire types in from an existing openapi spec.

Thanks!

**Comment by drwpow** [comment]
I really like the idea of adding it! But I don’t have time at the moment to add it myself. This is something I’d love a PR on and would gladly accept. If anyone is able to provide one it’d be much appreciated
