### ISSUE TITLE
allow self signed certificate when reading spec from remote

### ISSUE THREAD

**Issue by dabuside** [openapi-ts/openapi-typescript#907]
`openapi-typescript https://1.1.1.1/admin/swagger/doc.json  --output petstore.ts`

output
```
✨ openapi-typescript 5.1.1
(node:29072) UnhandledPromiseRejectionWarning: Error: unable to verify the first certificate
```

**Comment by AmroAlnajar** [comment]
Having the same issue, any updates on this?

**Comment by apacholik** [comment]
Node.js v18.6.0

```
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: self-signed certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1534:34)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket._finishInit (node:_tls_wrap:948:8)
    at ssl.onhandshakedone (node:_tls_wrap:729:12) {
  code: 'DEPTH_ZERO_SELF_SIGNED_CERT'
}
```

**Comment by phil-hudson-aon** [comment]
Any updates on this please?

**Comment by meijer3** [comment]
```
export NODE_TLS_REJECT_UNAUTHORIZED=0 - Mac
set NODE_TLS_REJECT_UNAUTHORIZED=0 - windows
export NODE_TLS_REJECT_UNAUTHORIZED=0 - linux
```
https://stackoverflow.com/questions/68592669/how-to-set-value-for-node-tls-reject-unauthorized-0-in-mac

**Comment by drwpow** [comment]
In 5.x and 6.x, fetching is handled by undici. Undici has added self-signed certificates support ([docs](https://undici.nodejs.org/#/docs/best-practices/client-certificate)), and I’d be open to adding a CLI flag.

However, in 7.x, the Redocly CLI is doing the schema fetching, and I think that doesn’t support it either, [as indicated in this open issue](https://github.com/Redocly/redocly-cli/issues/1017).

As much as I’d hate to introduce a new feature to 6.x right before it becomes obsolete in the next month or so, maybe we add it anyway, and work with Redocly to add it to the CLI so everyone wins
