### ISSUE TITLE
option to modify paths prefixes

### ISSUE THREAD

**Issue by maapteh** [openapi-ts/openapi-typescript#926]
Hi in toolings like Orval and Rapini you can replace the paths context. This is handy for clients who use a specific context in their frontend to point to that api. So example my service swagger tells endpoint is `/profile` but in our application we use `/api/profile` to internally forward to that service container.

Is this a feature you think adds value for your library? At the moment i can't use this library because of it but im first checking.

**Comment by drwpow** [comment]
Ah that’s really interesting. Does your schema take advantage of the [servers](https://swagger.io/specification/) part of the config? There could be something done with that automatically.

**Comment by maapteh** [comment]
@drwpow  Its a microservice, so they don't really care where you expose things on the frontend application. Multiple apps use the same service but expose differently. This path can then be used in toolings like openapi-typescript-fetch (like this lib advises) to be really typesafe and more!
